let shopItems =[
    {
        "id": 1,
        "name" :"Negoni" ,
        "price":"550" ,
       "content":"lorem 3fqfg gks sk gs g+s sjbsf sf sefb e gs" , 
       "img":"./assest/Negroni.png",
       "making":"Click here for:KIET ERP Portal KIET Web Site KIET Email Office o365 Login For any type of IT services please Contact us: Email- itsupport@kiet.edu, Helpline and whatsapp No:8744097774 (Please ignore calls on personal mobile number)",
    },
    {
        "id":2 ,
        "name" :"Blue lagoon" ,
        "price":"450" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "making":"* first",
       "img":"./assest/blue lagoon.png",

    },
    {
        "id":3 ,
        "name" :"Boulevardier",
        "price":"680" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/Boulevardier.png",
       "making":"* first",
    },
    {
        "id":4 ,
        "name" :"Espresso Martini",
        "price":"700" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/Espresso Martini.png",
       "making":"* first",
    },
    {
        "id":5 ,
        "name" :"Gimlet" ,
        "price":"600" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/Gimlet.png",
       "making":"* first",
    },
    {
        "id":6 ,
        "name" :"luckin" ,
        "price":"550" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/luckin.png",
       "making":"* first",
    },
    {
        "id":7 ,
        "name" :"Mai Tai" ,
        "price":"650" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/Mai Tai.png",
       "making":"* first",
       
    },
    {
        "id": 8,
        "name" :"Mimosa" ,
        "price":"820" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/Mimosa.png",
       "making":"* first",
    },
    {
        "id":9 ,
        "name" :"Mojito" ,
        "price":"340" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/Mojito.png",
       "making":"* first",
    },
    {
        "id": 10,
        "name" :"Orange" ,
        "price":"120" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/Orange.png",
       "making":"* first",
    },
    {
        "id":11 ,
        "name" :"Sangria" ,
        "price":"340" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/sangria.png",
       "making":"* first",
    },
    {
        "id": 12,
        "name" :"Sarec" ,
        "price":"200" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/Sarec.png",
       "making":"* first",
    },
    {
        "id": 13,
        "name" :"Smoothie" ,
        "price":"240" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/sangria.png",
       "making":"* first",
    },
    {
        "id": 14,
        "name" :"Empathy" ,
        "price":"2000" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/White Russian.png",
       "making":"* first",
    },
    {
        "id": 15,
        "name" :"Wignac" ,
        "price":"3000" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/Belaire.png",
       "making":"* first",
    },
    {
        "id": 16,
        "name" :"Mojitoo" ,
        "price":"200" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/Mojitoo.png",
       "making":"* first",

    },
    {
        "id": 17,
        "name" :"luckin" ,
        "price":"200" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/luckin.png",
       "making":"* first",
    },
    {
        "id": 18,
        "name" :"sangria" ,
        "price":"300" ,
       "content":"lorem 3fqfg gks sk gs gs sjbsf sf sef djjw  dn" , 
       "img":"./assest/sangria.png",
       "making":"* first",
    },
    
    ]